#Generated Form Function
function GenerateResponse($challengeItem,$length){
	$longanswer = ($challengeItem * (81521 + $length))
	$response = $longanswer.ToString()
	$response = $response.Substring(4,5)
	$response
}

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#####################################################
######### BEGIN USER CONFIGURABLE CODE HERE #########
#####################################################
#Check appropriate user account membership
$securityGroup = ""
$Recurse = $true
Add-Type -AssemblyName System.DirectoryServices.AccountManagement
$ct = [System.DirectoryServices.AccountManagement.ContextType]::Domain
$Group = [System.DirectoryServices.AccountManagement.GroupPrincipal]::FindByIdentity($ct,$securityGroup)
if(($Group.GetMembers($Recurse).SamAccountName) -notcontains "$env:USERNAME"){
	[System.Windows.Forms.MessageBox]::Show("Unauthorized User!")
	Exit
}
###################################################
######### END USER CONFIGURABLE CODE HERE #########
###################################################

function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 1/7/2015 3:38 PM
# Generated By: Zieh2409
########################################################################

#region Generated Form Objects
$main = New-Object System.Windows.Forms.Form
$label_Hours = New-Object System.Windows.Forms.Label
$combo_Hours = New-Object System.Windows.Forms.ComboBox
$label_Delay = New-Object System.Windows.Forms.Label
$button_Submit = New-Object System.Windows.Forms.Button
$BoxResponse4 = New-Object System.Windows.Forms.TextBox
$BoxResponse3 = New-Object System.Windows.Forms.TextBox
$BoxResponse2 = New-Object System.Windows.Forms.TextBox
$BoxResponse1 = New-Object System.Windows.Forms.TextBox
$BoxChallenge4 = New-Object System.Windows.Forms.TextBox
$BoxChallenge3 = New-Object System.Windows.Forms.TextBox
$BoxChallenge2 = New-Object System.Windows.Forms.TextBox
$BoxChallenge1 = New-Object System.Windows.Forms.TextBox
$label_Response = New-Object System.Windows.Forms.Label
$label_Challenge = New-Object System.Windows.Forms.Label
$label_Description = New-Object System.Windows.Forms.Label
$label_Title = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$button_Submit_OnClick= 
{
	if(-not ($combo_Hours.Text -eq "")){
		if(($BoxChallenge1.Text -match "^\d{5}$") -and ($BoxChallenge1.Text -match "^\d{5}$") -and ($BoxChallenge1.Text -match "^\d{5}$") -and ($BoxChallenge1.Text -match "^\d{5}$")){
			#Generate Response Code
			[int]$challenge1 = [convert]::ToInt32($BoxChallenge1.Text,10) + 1111
			[int]$challenge2 = [convert]::ToInt32($BoxChallenge2.Text,10) + 2222
			[int]$challenge3 = [convert]::ToInt32($BoxChallenge3.Text,10) + 3333
			[int]$challenge4 = [convert]::ToInt32($BoxChallenge4.Text,10) + 4444
			[int]$hours = [convert]::ToInt32($combo_Hours.Text,10)

			$BoxResponse1.Text = GenerateResponse $challenge1 $hours
			$BoxResponse2.Text = GenerateResponse $challenge2 $hours
			$BoxResponse3.Text = GenerateResponse $challenge3 $hours
			$BoxResponse4.Text = GenerateResponse $challenge4 $hours
		}else{
			[System.Windows.Forms.MessageBox]::Show("Incorrect Challenge!")
		}
	}else{
		[System.Windows.Forms.MessageBox]::Show("Delay Not Selected!")
	}
}

$handler_main_Load= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$main.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$main.BackColor = [System.Drawing.Color]::FromArgb(255,255,239,213)
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 189
$System_Drawing_Size.Width = 512
$main.ClientSize = $System_Drawing_Size
$main.DataBindings.DefaultDataSourceUpdateMode = 0
$main.FormBorderStyle = 1
$main.Name = "main"
$main.Text = "Emergency Reboot Delay"
$main.add_Load($handler_main_Load)

$label_Hours.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 140
$System_Drawing_Point.Y = 130
$label_Hours.Location = $System_Drawing_Point
$label_Hours.Name = "label_Hours"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 17
$System_Drawing_Size.Width = 100
$label_Hours.Size = $System_Drawing_Size
$label_Hours.TabIndex = 0
$label_Hours.Text = "Hour(s)"

$main.Controls.Add($label_Hours)

$combo_Hours.DataBindings.DefaultDataSourceUpdateMode = 0
$combo_Hours.DropDownStyle = 2
$combo_Hours.FormattingEnabled = $True
$combo_Hours.Items.Add("1")|Out-Null
$combo_Hours.Items.Add("2")|Out-Null
$combo_Hours.Items.Add("3")|Out-Null
$combo_Hours.Items.Add("4")|Out-Null
$combo_Hours.Items.Add("5")|Out-Null
$combo_Hours.Items.Add("6")|Out-Null
$combo_Hours.Items.Add("7")|Out-Null
$combo_Hours.Items.Add("8")|Out-Null
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 81
$System_Drawing_Point.Y = 127
$combo_Hours.Location = $System_Drawing_Point
$combo_Hours.Name = "combo_Hours"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 53
$combo_Hours.Size = $System_Drawing_Size
$combo_Hours.TabIndex = 5

$main.Controls.Add($combo_Hours)

$label_Delay.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 130
$label_Delay.Location = $System_Drawing_Point
$label_Delay.Name = "label_Delay"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 17
$System_Drawing_Size.Width = 61
$label_Delay.Size = $System_Drawing_Size
$label_Delay.TabIndex = 0
$label_Delay.Text = "Delay:"

$main.Controls.Add($label_Delay)


$button_Submit.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 371
$System_Drawing_Point.Y = 154
$button_Submit.Location = $System_Drawing_Point
$button_Submit.Name = "button_Submit"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 129
$button_Submit.Size = $System_Drawing_Size
$button_Submit.TabIndex = 6
$button_Submit.Text = "Generate Response"
$button_Submit.UseVisualStyleBackColor = $True
$button_Submit.add_Click($button_Submit_OnClick)

$main.Controls.Add($button_Submit)

$BoxResponse4.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 399
$System_Drawing_Point.Y = 101
$BoxResponse4.Location = $System_Drawing_Point
$BoxResponse4.Name = "BoxResponse4"
$BoxResponse4.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$BoxResponse4.Size = $System_Drawing_Size
$BoxResponse4.TabIndex = 0
$BoxResponse4.TabStop = $False

$main.Controls.Add($BoxResponse4)

$BoxResponse3.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 293
$System_Drawing_Point.Y = 101
$BoxResponse3.Location = $System_Drawing_Point
$BoxResponse3.Name = "BoxResponse3"
$BoxResponse3.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$BoxResponse3.Size = $System_Drawing_Size
$BoxResponse3.TabIndex = 0
$BoxResponse3.TabStop = $False

$main.Controls.Add($BoxResponse3)

$BoxResponse2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 187
$System_Drawing_Point.Y = 101
$BoxResponse2.Location = $System_Drawing_Point
$BoxResponse2.Name = "BoxResponse2"
$BoxResponse2.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$BoxResponse2.Size = $System_Drawing_Size
$BoxResponse2.TabIndex = 0
$BoxResponse2.TabStop = $False

$main.Controls.Add($BoxResponse2)

$BoxResponse1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 81
$System_Drawing_Point.Y = 101
$BoxResponse1.Location = $System_Drawing_Point
$BoxResponse1.Name = "BoxResponse1"
$BoxResponse1.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$BoxResponse1.Size = $System_Drawing_Size
$BoxResponse1.TabIndex = 0
$BoxResponse1.TabStop = $False

$main.Controls.Add($BoxResponse1)

$BoxChallenge4.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 399
$System_Drawing_Point.Y = 75
$BoxChallenge4.Location = $System_Drawing_Point
$BoxChallenge4.Name = "BoxChallenge4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$BoxChallenge4.Size = $System_Drawing_Size
$BoxChallenge4.TabIndex = 4

$main.Controls.Add($BoxChallenge4)

$BoxChallenge3.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 293
$System_Drawing_Point.Y = 75
$BoxChallenge3.Location = $System_Drawing_Point
$BoxChallenge3.Name = "BoxChallenge3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$BoxChallenge3.Size = $System_Drawing_Size
$BoxChallenge3.TabIndex = 3

$main.Controls.Add($BoxChallenge3)

$BoxChallenge2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 187
$System_Drawing_Point.Y = 75
$BoxChallenge2.Location = $System_Drawing_Point
$BoxChallenge2.Name = "BoxChallenge2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$BoxChallenge2.Size = $System_Drawing_Size
$BoxChallenge2.TabIndex = 2

$main.Controls.Add($BoxChallenge2)

$BoxChallenge1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 81
$System_Drawing_Point.Y = 75
$BoxChallenge1.Location = $System_Drawing_Point
$BoxChallenge1.Name = "BoxChallenge1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$BoxChallenge1.Size = $System_Drawing_Size
$BoxChallenge1.TabIndex = 1

$main.Controls.Add($BoxChallenge1)

$label_Response.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 104
$label_Response.Location = $System_Drawing_Point
$label_Response.Name = "label_Response"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 17
$System_Drawing_Size.Width = 61
$label_Response.Size = $System_Drawing_Size
$label_Response.TabIndex = 0
$label_Response.Text = "Response:"

$main.Controls.Add($label_Response)

$label_Challenge.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 78
$label_Challenge.Location = $System_Drawing_Point
$label_Challenge.Name = "label_Challenge"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 17
$System_Drawing_Size.Width = 61
$label_Challenge.Size = $System_Drawing_Size
$label_Challenge.TabIndex = 0
$label_Challenge.Text = "Challenge:"

$main.Controls.Add($label_Challenge)

$label_Description.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 40
$label_Description.Location = $System_Drawing_Point
$label_Description.Name = "label_Description"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 32
$System_Drawing_Size.Width = 486
$label_Description.Size = $System_Drawing_Size
$label_Description.TabIndex = 0
$label_Description.Text = "This utility generates the response code for users requesting a delay in reboots. `nYou need to input the challenge and the delay requested by the user."
$label_Description.TextAlign = 2

$main.Controls.Add($label_Description)

$label_Title.DataBindings.DefaultDataSourceUpdateMode = 0
$label_Title.Font = New-Object System.Drawing.Font("Segoe UI",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 13
$label_Title.Location = $System_Drawing_Point
$label_Title.Name = "label_Title"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 486
$label_Title.Size = $System_Drawing_Size
$label_Title.TabIndex = 0
$label_Title.Text = "Emergency Reboot Delay Response Generator"
$label_Title.TextAlign = 2

$main.Controls.Add($label_Title)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $main.WindowState
#Init the OnLoad event to correct the initial state of the form
$main.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$main.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
